conky.config = {
    own_window = true,
    own_window_type = 'dock',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_transparent = true,

    out_to_x = false,
    out_to_wayland = true,
    double_buffer = true,
    update_interval = 2,

    minimum_width = 250,
    maximum_width = 250,
    minimum_height = 100,
    alignment = 'top_right',
    gap_x = 30,
    gap_y = 130,

    use_xft = true,
    font = 'Fira Code:size=12',
    default_color = '#2fffff',

    draw_borders = true,
    border_width = 2,
    border_inner_margin = 12,

    background = false,
};

conky.text = [[
${alignc}${font Fira Code:size=10}CPU$font
${voffset -50}
${font Fira Code:size=10}
Total  ${alignr}${cpu cpu0}%
${cpubar cpu0 8,220}

C1 ${cpu cpu1}%  ${cpubar cpu1 6,160}
C2 ${cpu cpu2}%  ${cpubar cpu2 6,160}
C3 ${cpu cpu3}%  ${cpubar cpu3 6,160}
C4 ${cpu cpu4}%  ${cpubar cpu4 6,160}
C5 ${cpu cpu5}%  ${cpubar cpu5 6,160}
C6 ${cpu cpu6}%  ${cpubar cpu6 6,160}

Freq ${alignr}${freq_g} GHz
${voffset -50}
$font
]];
