conky.config = {
    own_window = true,
    own_window_type = 'dock',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_transparent = true,

    out_to_x = false,
    out_to_wayland = true,
    double_buffer = true,
    update_interval = 2,

    minimum_width = 1200,
    maximum_width = 1200,
    minimum_height = 180,
    maximum_height = 180,
    alignment = 'bottom_middle',   -- center bottom
    gap_x = 0,
    gap_y = 35,

    use_xft = true,
    font = 'Fira Code:size=11',
    default_color = '#2fffff',

    draw_borders = true,
    border_width = 2,
    border_inner_margin = 12,

    background = false,
};

conky.text = [[
${alignc}${font Fira Code:size=10}LOGS$font
${voffset -8}
${font Fira Code:size=11}
${execi 2 journalctl -n 8 -o short --no-pager 2>/dev/null | fold -w 140}
$font
]];
