conky.config = {
    own_window = true,
    own_window_type = 'dock',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_transparent = true,

    out_to_x = false,
    out_to_wayland = true,
    double_buffer = true,
    update_interval = 2,

    minimum_width = 250,
    maximum_width = 250,
    minimum_height = 50,
    alignment = 'top_right',
    gap_x = 30,
    gap_y = 360,   -- BELOW cpu (adjust if needed)

    use_xft = true,
    font = 'Fira Code:size=12',
    default_color = '#2fffff',

    draw_borders = true,
    border_width = 2,
    border_inner_margin = 12,

    background = false,
};

conky.text = [[
${alignc}${font Fira Code:size=10}MEMORY$font
${voffset -50}
${font Fira Code:size=10}
RAM ${alignr}$memperc%
${membar 8,220}

Used ${alignr}$mem / $memmax
Free ${alignr}$memfree

Swap ${alignr}$swapperc%
${swapbar 6,220}
${voffset -50}
$font
]];
