conky.config = {
    own_window = true,
    own_window_type = 'dock',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_transparent = true,

    out_to_x = false,
    out_to_wayland = true,
    double_buffer = true,
    update_interval = 2,

    minimum_width = 250,
    maximum_width = 250,
    minimum_height = 90,
    alignment = 'top_right',
    gap_x = 30,
    gap_y = 830,   

    use_xft = true,
    font = 'Fira Code:size=10',
    default_color = '#2fffff',

    draw_borders = true,
    border_width = 2,
    border_inner_margin = 12,

    background = false,
};

conky.text = [[
${alignc}PLAY
${voffset -30}

${execi 2 playerctl metadata --format '{{title}}' 2>/dev/null || echo "—"}

${alignc}${execi 2 playerctl position 2>/dev/null | awk '{printf "%02d:%02d", int($1/60), int($1%60)}'} \
/ \
${execi 2 playerctl metadata mpris:length 2>/dev/null | awk '{printf "%02d:%02d", int($1/1000000/60), int(($1/1000000)%60)}'}
]];
