conky.config = {
    own_window = true,
    own_window_type = 'dock',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_transparent = true,

    out_to_x = false,
    out_to_wayland = true,
    double_buffer = true,
    update_interval = 10,

    minimum_width = 250,
    maximum_width = 250,
    minimum_height = 400,
    alignment = 'top_left',   -- same anchor as others
    gap_x = 30,
    gap_y = 580,              -- push BELOW calendar (tweak if needed)

    use_xft = true,
    font = 'Fira Code:size=13',
    default_color = '#2fffff',

    -- border
    draw_borders = true,
    border_width = 2,
    border_inner_margin = 12,

    background = false,
};

conky.text = [[
${alignc}${font Fira Code:bold:size=10}TODO$font

${font Fira Code:size=13}${exec cat ~/.config/conky/todo.txt 2>/dev/null || echo "No tasks"}$font
]];
