# =========================
# Playback
# =========================

SPACE cycle pause
q quit
Q quit-watch-later
f cycle fullscreen

# Seek
LEFT seek -5
RIGHT seek 5

SHIFT+LEFT seek -60
SHIFT+RIGHT seek 60

UP seek 30
DOWN seek -30

# Frame stepping
. frame-step
, frame-back-step

# =========================
# Volume
# =========================

9 add volume -2
0 add volume 2

m cycle mute

# =========================
# Subtitles
# =========================

v cycle sub
j sub-seek -1
J sub-seek 1

z add sub-delay -0.1
x add sub-delay 0.1

# =========================
# Audio tracks
# =========================

# cycle audio track
a cycle audio

# Audio delay
[ add audio-delay -0.1
] add audio-delay 0.1

# =========================
# Speed
# =========================

[ multiply speed 0.9091
] multiply speed 1.1

BACKSPACE set speed 1.0

# =========================
# Screenshots
# =========================

s screenshot

# =========================
# Playlist
# =========================

n playlist-next
p playlist-prev